<script>
  import { assets } from '$app/paths';
  let width = null;
  import { onMount } from 'svelte';
  export let onAiMounted = () => {};
  onMount(() => {
    onAiMounted();
  });
</script>

<!-- Generated by ai2html v0.100.0 - 2022-06-23 00:00 -->

<div id="g-d3-map-hillshaded-box" bind:clientWidth="{width}">
  <!-- Artboard: xs -->
  {#if width && width >= 0 && width < 510}
    <div id="g-d3-map-hillshaded-xs" class="g-artboard" style="">
      <div style="padding: 0 0 65.4113% 0;"></div>
      <div
        id="g-d3-map-hillshaded-xs-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/d3-map-hillshaded-xs.jpg);"
      ></div>
    </div>
  {/if}
  <!-- Artboard: sm -->
  {#if width && width >= 510 && width < 660}
    <div id="g-d3-map-hillshaded-sm" class="g-artboard" style="">
      <div style="padding: 0 0 65.3458% 0;"></div>
      <div
        id="g-d3-map-hillshaded-sm-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/d3-map-hillshaded-sm.jpg);"
      ></div>
    </div>
  {/if}
  <!-- Artboard: md -->
  {#if width && width >= 660 && width < 930}
    <div id="g-d3-map-hillshaded-md" class="g-artboard" style="">
      <div style="padding: 0 0 65.461% 0;"></div>
      <div
        id="g-d3-map-hillshaded-md-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/d3-map-hillshaded-md.jpg);"
      ></div>
    </div>
  {/if}
  <!-- Artboard: lg -->
  {#if width && width >= 930 && width < 1200}
    <div id="g-d3-map-hillshaded-lg" class="g-artboard" style="">
      <div style="padding: 0 0 65.461% 0;"></div>
      <div
        id="g-d3-map-hillshaded-lg-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/d3-map-hillshaded-lg.jpg);"
      ></div>
    </div>
  {/if}
  <!-- Artboard: xl -->
  {#if width && width >= 1200}
    <div id="g-d3-map-hillshaded-xl" class="g-artboard" style="">
      <div style="padding: 0 0 65.461% 0;"></div>
      <div
        id="g-d3-map-hillshaded-xl-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/d3-map-hillshaded-xl.jpg);"
      ></div>
    </div>
  {/if}
</div>
<!-- End ai2html - 2022-06-23 00:00 -->

<!-- ai file: d3-map-hillshaded.ai -->
<style lang="scss">
  #g-d3-map-hillshaded-box,
  #g-d3-map-hillshaded-box .g-artboard {
    margin: 0 auto;
  }
  #g-d3-map-hillshaded-box p {
    margin: 0;
  }
  #g-d3-map-hillshaded-box .g-aiAbs {
    position: absolute;
  }
  #g-d3-map-hillshaded-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }
  #g-d3-map-hillshaded-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-d3-map-hillshaded-xs {
    position: relative;
    overflow: hidden;
  }
  #g-d3-map-hillshaded-sm {
    position: relative;
    overflow: hidden;
  }
  #g-d3-map-hillshaded-md {
    position: relative;
    overflow: hidden;
  }
  #g-d3-map-hillshaded-lg {
    position: relative;
    overflow: hidden;
  }
  #g-d3-map-hillshaded-xl {
    position: relative;
    overflow: hidden;
  }

  /* Custom CSS */
</style>
