<script>
  import { assets } from '$app/paths';
  let width = null;
  import { onMount } from 'svelte';
  export let onAiMounted = () => {};
  onMount(() => {
    onAiMounted();
  });
</script>

<!-- Generated by ai2html v0.100.0 - 2022-07-08 12:04 -->

<div id="g-d3-map-hillshaded-aoc-mar23-box" bind:clientWidth="{width}">
  <!-- Artboard: md -->
  {#if width && width >= 0 && width < 930}
    <div id="g-d3-map-hillshaded-aoc-mar23-md" class="g-artboard" style="">
      <div style="padding: 0 0 65.461% 0;"></div>
      <div
        id="g-d3-map-hillshaded-aoc-mar23-md-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/d3-map-hillshaded-aoc-mar23-md.svg);"
      ></div>
    </div>
  {/if}
  <!-- Artboard: lg -->
  {#if width && width >= 930 && width < 1200}
    <div id="g-d3-map-hillshaded-aoc-mar23-lg" class="g-artboard" style="">
      <div style="padding: 0 0 65.461% 0;"></div>
      <div
        id="g-d3-map-hillshaded-aoc-mar23-lg-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/d3-map-hillshaded-aoc-mar23-lg.svg);"
      ></div>
    </div>
  {/if}
  <!-- Artboard: xl -->
  {#if width && width >= 1200}
    <div id="g-d3-map-hillshaded-aoc-mar23-xl" class="g-artboard" style="">
      <div style="padding: 0 0 65.461% 0;"></div>
      <div
        id="g-d3-map-hillshaded-aoc-mar23-xl-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/d3-map-hillshaded-aoc-mar23-xl.svg);"
      ></div>
    </div>
  {/if}
</div>
<!-- End ai2html - 2022-07-08 12:04 -->

<!-- ai file: d3-map-hillshaded.ai -->
<style lang="scss">
  #g-d3-map-hillshaded-aoc-mar23-box,
  #g-d3-map-hillshaded-aoc-mar23-box .g-artboard {
    margin: 0 auto;
  }
  #g-d3-map-hillshaded-aoc-mar23-box p {
    margin: 0;
  }
  #g-d3-map-hillshaded-aoc-mar23-box .g-aiAbs {
    position: absolute;
  }
  #g-d3-map-hillshaded-aoc-mar23-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }
  #g-d3-map-hillshaded-aoc-mar23-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-d3-map-hillshaded-aoc-mar23-md {
    position: relative;
    overflow: hidden;
  }
  #g-d3-map-hillshaded-aoc-mar23-lg {
    position: relative;
    overflow: hidden;
  }
  #g-d3-map-hillshaded-aoc-mar23-xl {
    position: relative;
    overflow: hidden;
  }

  /* Custom CSS */
</style>
