<script>
  import { assets } from '$app/paths';
  let width = null;
  import { onMount } from 'svelte';
  export let onAiMounted = () => {};
  onMount(() => {
    onAiMounted();
  });
</script>

<!-- Generated by ai2html v0.100.0 - 2022-07-04 12:01 -->

<div id="g-d3-map-hillshaded-labels-box" bind:clientWidth="{width}">
  <!-- Artboard: md -->
  {#if width && width >= 0 && width < 930}
    <div id="g-d3-map-hillshaded-labels-md" class="g-artboard" style="">
      <div style="padding: 0 0 65.461% 0;"></div>
      <div
        id="g-d3-map-hillshaded-labels-md-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/d3-map-hillshaded-labels-md.png);"
      ></div>
      <div
        id="g-ai0-1"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:27.095%;margin-top:-12.1px;left:85.884%;margin-left:-65.5px;width:131px;"
      >
        <p class="g-pstyle0">RUSSIA</p>
      </div>
      <div
        id="g-ai0-2"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:48.1578%;margin-top:-12.1px;left:52.5091%;margin-left:-76.5px;width:153px;"
      >
        <p class="g-pstyle0">UKRAINE</p>
      </div>
      <div
        id="g-ai0-3"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:57.2457%;margin-top:-9.3px;left:5.817%;margin-left:-44px;width:88px;"
      >
        <p class="g-pstyle1">HUNGARY</p>
      </div>
      <div
        id="g-ai0-4"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:66.5041%;margin-top:-9.3px;left:15.1425%;margin-left:-42.5px;width:85px;"
      >
        <p class="g-pstyle1">ROMANIA</p>
      </div>
      <div
        id="g-ai0-5"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:76.7573%;margin-top:-7.6px;left:75.3522%;margin-left:-43px;width:86px;"
      >
        <p class="g-pstyle2">Sea of Azov</p>
      </div>
      <div
        id="g-ai0-6"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:81.7804%;margin-top:-9.3px;left:62.7686%;margin-left:-34px;width:68px;"
      >
        <p class="g-pstyle3">Crimea</p>
      </div>
      <div
        id="g-ai0-7"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:87.6358%;margin-top:-7.6px;left:48.979%;margin-left:-38.5px;width:77px;"
      >
        <p class="g-pstyle2">Black Sea</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: lg -->
  {#if width && width >= 930 && width < 1200}
    <div id="g-d3-map-hillshaded-labels-lg" class="g-artboard" style="">
      <div style="padding: 0 0 65.461% 0;"></div>
      <div
        id="g-d3-map-hillshaded-labels-lg-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/d3-map-hillshaded-labels-lg.png);"
      ></div>
      <div
        id="g-ai1-1"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:9.9092%;margin-top:-9.3px;left:34.2551%;margin-left:-62px;width:124px;"
      >
        <p class="g-pstyle0">BELARUS</p>
      </div>
      <div
        id="g-ai1-2"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:13.3587%;margin-top:-9.3px;left:8.3249%;margin-left:-56px;width:112px;"
      >
        <p class="g-pstyle0">POLAND</p>
      </div>
      <div
        id="g-ai1-3"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:27.4418%;margin-top:-12.1px;left:84.6759%;margin-left:-65.5px;width:131px;"
      >
        <p class="g-pstyle1">RUSSIA</p>
      </div>
      <div
        id="g-ai1-4"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:42.8823%;margin-top:-12.1px;left:44.3892%;margin-left:-76.5px;width:153px;"
      >
        <p class="g-pstyle1">UKRAINE</p>
      </div>
      <div
        id="g-ai1-5"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:48.0177%;margin-top:-9.3px;left:5.051%;margin-left:-38.5px;width:77px;"
      >
        <p class="g-pstyle2">SLOVAKIA</p>
      </div>
      <div
        id="g-ai1-6"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:57.7091%;margin-top:-9.3px;left:5.9729%;margin-left:-44px;width:88px;"
      >
        <p class="g-pstyle3">HUNGARY</p>
      </div>
      <div
        id="g-ai1-7"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:59.8445%;margin-top:-9.3px;left:36.781%;margin-left:-44.5px;width:89px;"
      >
        <p class="g-pstyle3">MOLDOVA</p>
      </div>
      <div
        id="g-ai1-8"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:75.6626%;margin-top:-7.6px;left:74.6644%;margin-left:-43px;width:86px;"
      >
        <p class="g-pstyle4">Sea of Azov</p>
      </div>
      <div
        id="g-ai1-9"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:77.2562%;margin-top:-9.3px;left:20.5451%;margin-left:-42.5px;width:85px;"
      >
        <p class="g-pstyle3">ROMANIA</p>
      </div>
      <div
        id="g-ai1-10"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:82.6769%;margin-top:-9.3px;left:63.9625%;margin-left:-34px;width:68px;"
      >
        <p class="g-pstyle5">Crimea</p>
      </div>
      <div
        id="g-ai1-11"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:82.3973%;margin-top:-7.6px;left:50.9352%;margin-left:-38.5px;width:77px;"
      >
        <p class="g-pstyle4">Black Sea</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: xl -->
  {#if width && width >= 1200}
    <div id="g-d3-map-hillshaded-labels-xl" class="g-artboard" style="">
      <div style="padding: 0 0 65.461% 0;"></div>
      <div
        id="g-d3-map-hillshaded-labels-xl-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/d3-map-hillshaded-labels-xl.png);"
      ></div>
      <div
        id="g-ai2-1"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:9.301%;margin-top:-12.1px;left:38.1265%;margin-left:-76.5px;width:153px;"
      >
        <p class="g-pstyle0">BELARUS</p>
      </div>
      <div
        id="g-ai2-2"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:17.321%;margin-top:-12.1px;left:10.2558%;margin-left:-69px;width:138px;"
      >
        <p class="g-pstyle0">POLAND</p>
      </div>
      <div
        id="g-ai2-3"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:27.2806%;margin-top:-14.3px;left:83.3962%;margin-left:-78px;width:156px;"
      >
        <p class="g-pstyle1">RUSSIA</p>
      </div>
      <div
        id="g-ai2-4"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:44.4664%;margin-top:-14.3px;left:43.7141%;margin-left:-91px;width:182px;"
      >
        <p class="g-pstyle1">UKRAINE</p>
      </div>
      <div
        id="g-ai2-5"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:46.2186%;margin-top:-12.1px;left:4.3556%;margin-left:-46.5px;width:93px;"
      >
        <p class="g-pstyle2">SLOVAKIA</p>
      </div>
      <div
        id="g-ai2-6"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:57.2939%;margin-top:-12.1px;left:6.3449%;margin-left:-53.5px;width:107px;"
      >
        <p class="g-pstyle3">HUNGARY</p>
      </div>
      <div
        id="g-ai2-7"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:59.4581%;margin-top:-12.1px;left:36.8319%;margin-left:-54px;width:108px;"
      >
        <p class="g-pstyle3">MOLDOVA</p>
      </div>
      <div
        id="g-ai2-8"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:75.0101%;margin-top:-9.2px;left:76.0321%;margin-left:-48px;width:96px;"
      >
        <p class="g-pstyle4">Sea of Azov</p>
      </div>
      <div
        id="g-ai2-9"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:76.6439%;margin-top:-12.1px;left:20.8064%;margin-left:-52px;width:104px;"
      >
        <p class="g-pstyle3">ROMANIA</p>
      </div>
      <div
        id="g-ai2-10"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:81.7571%;margin-top:-9.2px;left:50.8393%;margin-left:-43px;width:86px;"
      >
        <p class="g-pstyle4">Black Sea</p>
      </div>
      <div
        id="g-ai2-11"
        class="g-labels g-aiAbs g-aiPointText"
        style="top:82.6271%;margin-top:-12.1px;left:63.7765%;margin-left:-40.5px;width:81px;"
      >
        <p class="g-pstyle5">Crimea</p>
      </div>
    </div>
  {/if}
</div>
<!-- End ai2html - 2022-07-04 12:01 -->

<!-- ai file: d3-map-hillshaded.ai -->
<style lang="scss">
  #g-d3-map-hillshaded-labels-box,
  #g-d3-map-hillshaded-labels-box .g-artboard {
    margin: 0 auto;
  }
  #g-d3-map-hillshaded-labels-box p {
    margin: 0;
  }
  #g-d3-map-hillshaded-labels-box .g-aiAbs {
    position: absolute;
  }
  #g-d3-map-hillshaded-labels-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }
  #g-d3-map-hillshaded-labels-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-d3-map-hillshaded-labels-md {
    position: relative;
    overflow: hidden;
  }
  #g-d3-map-hillshaded-labels-md p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 300;
    font-style: normal;
    line-height: 14px;
    height: auto;
    opacity: 1;
    letter-spacing: 0.079em;
    font-size: 12px;
    text-align: left;
    color: rgb(153, 153, 153);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    position: static;
  }
  #g-d3-map-hillshaded-labels-md .g-pstyle0 {
    font-weight: 400;
    line-height: 22px;
    height: 22px;
    letter-spacing: 0.502em;
    font-size: 18px;
    text-align: center;
    color: rgb(132, 132, 132);
  }
  #g-d3-map-hillshaded-labels-md .g-pstyle1 {
    line-height: 17px;
    height: 17px;
    letter-spacing: 0.1em;
    font-size: 14px;
    text-align: center;
  }
  #g-d3-map-hillshaded-labels-md .g-pstyle2 {
    font-style: italic;
    height: 14px;
    text-align: center;
  }
  #g-d3-map-hillshaded-labels-md .g-pstyle3 {
    font-weight: 400;
    line-height: 17px;
    height: 17px;
    letter-spacing: 0.05em;
    font-size: 14px;
    text-align: center;
    color: rgb(132, 132, 132);
  }
  #g-d3-map-hillshaded-labels-lg {
    position: relative;
    overflow: hidden;
  }
  #g-d3-map-hillshaded-labels-lg p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 300;
    line-height: 17px;
    height: auto;
    opacity: 1;
    letter-spacing: 0.1em;
    font-size: 14px;
    text-align: left;
    color: rgb(153, 153, 153);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-d3-map-hillshaded-labels-lg .g-pstyle0 {
    height: 17px;
    letter-spacing: 0.502em;
    text-align: center;
  }
  #g-d3-map-hillshaded-labels-lg .g-pstyle1 {
    font-weight: 400;
    line-height: 22px;
    height: 22px;
    letter-spacing: 0.502em;
    font-size: 18px;
    text-align: center;
    color: rgb(132, 132, 132);
  }
  #g-d3-map-hillshaded-labels-lg .g-pstyle2 {
    height: 17px;
    letter-spacing: 0em;
    text-align: center;
  }
  #g-d3-map-hillshaded-labels-lg .g-pstyle3 {
    height: 17px;
    text-align: center;
  }
  #g-d3-map-hillshaded-labels-lg .g-pstyle4 {
    font-style: italic;
    line-height: 14px;
    height: 14px;
    letter-spacing: 0.079em;
    font-size: 12px;
    text-align: center;
  }
  #g-d3-map-hillshaded-labels-lg .g-pstyle5 {
    font-weight: 400;
    height: 17px;
    letter-spacing: 0.05em;
    text-align: center;
    color: rgb(132, 132, 132);
  }
  #g-d3-map-hillshaded-labels-xl {
    position: relative;
    overflow: hidden;
  }
  #g-d3-map-hillshaded-labels-xl p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 300;
    line-height: 22px;
    height: auto;
    opacity: 1;
    letter-spacing: 0.1em;
    font-size: 18px;
    text-align: left;
    color: rgb(153, 153, 153);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-d3-map-hillshaded-labels-xl .g-pstyle0 {
    height: 22px;
    letter-spacing: 0.502em;
    text-align: center;
  }
  #g-d3-map-hillshaded-labels-xl .g-pstyle1 {
    font-weight: 400;
    line-height: 26px;
    height: 26px;
    letter-spacing: 0.502em;
    font-size: 22px;
    text-align: center;
    color: rgb(132, 132, 132);
  }
  #g-d3-map-hillshaded-labels-xl .g-pstyle2 {
    height: 22px;
    letter-spacing: 0em;
    text-align: center;
  }
  #g-d3-map-hillshaded-labels-xl .g-pstyle3 {
    height: 22px;
    text-align: center;
  }
  #g-d3-map-hillshaded-labels-xl .g-pstyle4 {
    font-style: italic;
    line-height: 17px;
    height: 17px;
    letter-spacing: 0.079em;
    font-size: 14px;
    text-align: center;
  }
  #g-d3-map-hillshaded-labels-xl .g-pstyle5 {
    font-weight: 400;
    height: 22px;
    letter-spacing: 0.05em;
    text-align: center;
    color: rgb(132, 132, 132);
  }

  /* Custom CSS */
</style>
